name: Node CI
on:
  push:
    branches:
      - 'develop'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn, build and, firebase
        run: |
          yarn
          npm install -g firebase-tools
          yarn build
          firebase deploy --only hosting:dev-portfolio-2020-17688 --token=$FIREBASE_TOKEN --project portfolio-2020-17688 --non-interactive
        env:
          CI: true
          FIREBASE_TOKEN: 1//097N9lKmrpRtqCgYIARAAGAkSNwF-L9IrNxAmnbfrUX1UXK6bK3bIDuTCl0megHT5Ctj0Dmb8ThxOxQWhEJXx9uwOSev9mvdCehc

