name: Node CI PR verify pipeline

on:
  pull_request:
    branches:
      - 'develop'
      - 'master'

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 8
      - run: yarn
      - run: yarn lint
      - run: yarn build
    env:
      CI: true
